version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nailstore.cms
    ports:
      - 8989:80

  nginx:
    image: nginx:alpine
    container_name: nailstore.nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/default.conf
    depends_on:
      - app